parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Domain\User\Repository\UserRepository:
        tags: ['doctrine.repository_service']
